---
# Project Information
site_name: Marco test package
site_author: Marco Gancitano
site_description: Test package for marco

# Repository information
repo_name: mgancita/marco-test-package
repo_url: https://github.com/mgancita/marco-test-package
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Marco Gancitano

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mgancita
      name: mgancita on GitHub

# Page tree
nav:
  - Home: index.md
